/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp com.sun.dbus.frist.test.xml -i dbus.h -a adaptor
 *
 * qdbusxml2cpp is Copyright (C) 2016 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef ADAPTOR_H
#define ADAPTOR_H

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
#include "dbus.h"
QT_BEGIN_NAMESPACE
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;
QT_END_NAMESPACE

/*
 * Adaptor class for interface com.sun.dbus.frist.test
 */
class TestAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "com.sun.dbus.frist.test")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"com.sun.dbus.frist.test\">\n"
"    <method name=\"method1\">\n"
"      <arg direction=\"out\" type=\"b\"/>\n"
"      <arg direction=\"in\" type=\"i\" name=\"input\"/>\n"
"    </method>\n"
"  </interface>\n"
        "")
public:
    TestAdaptor(QObject *parent);
    virtual ~TestAdaptor();

public: // PROPERTIES
public Q_SLOTS: // METHODS
    bool method1(int input);
Q_SIGNALS: // SIGNALS
};

#endif
