/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp com.sun.dbus.frist.test.xml -i dbus.h -a adaptor
 *
 * qdbusxml2cpp is Copyright (C) 2016 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "adaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class TestAdaptor
 */

TestAdaptor::TestAdaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

TestAdaptor::~TestAdaptor()
{
    // destructor
}

bool TestAdaptor::method1(int input)
{
    // handle method call com.sun.dbus.frist.test.method1
    bool out0;
    QMetaObject::invokeMethod(parent(), "method1", Q_RETURN_ARG(bool, out0), Q_ARG(int, input));
    return out0;
}

